name:                recipe-ocr
version:             0.1.0.0
github:              "githubuser/recipe-ocr"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/recipe-ocr#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.2
- text >= 1.2
- bytestring >= 0.10.12
- mtl >= 2.2
- transformers >= 0.5.6
- persistent >= 2.11
- persistent-sqlite >= 2.11
- persistent-template >= 2.9
- monad-logger >= 0.3.36
- process >= 1.6
- temporary >= 1.3
- ilist >= 0.4
- servant >= 0.18.2
- servant-server >= 0.18.2
- servant-multipart >= 0.12
- wai >= 3.2
- warp >= 3.3
- aeson >= 1.5
- resource-pool >= 0.2.3
- filepath >= 1.4

library:
  source-dirs: src

default-extensions:
- BlockArguments
- LambdaCase
- MultiWayIf
- OverloadedStrings
- NamedFieldPuns
- MultiParamTypeClasses
- GeneralizedNewtypeDeriving
- RecordWildCards
- DeriveFunctor
- StandaloneDeriving
- ScopedTypeVariables
- TupleSections
- KindSignatures
- DeriveDataTypeable
- TypeApplications
- StarIsType
- GADTs
- RankNTypes
- EmptyDataDecls
- FlexibleContexts
- QuasiQuotes
- TemplateHaskell
- TypeFamilies
- DerivingStrategies
- DataKinds
- ConstraintKinds
- TypeOperators
- DeriveGeneric
- DerivingVia

executables:
  recipe-ocr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - recipe-ocr

tests:
  recipe-ocr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - recipe-ocr
